# Generated by Django 5.0.4 on 2024-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='file_url',
        ),
        migrations.AddField(
            model_name='dissertation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dissertations/'),
        ),
    ]
