# Generated by Django 5.0.4 on 2024-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
